"""Shared enumerations for A-CONTRACT v1.1.0."""

from enum import StrEnum


class DocumentFormat(StrEnum):
    PDF = "PDF"
    DOCX = "DOCX"
    MARKDOWN = "MARKDOWN"
    TEXT = "TEXT"


class DocumentType(StrEnum):
    DATASHEET = "DATASHEET"
    TECHNICAL_MANUAL = "TECHNICAL_MANUAL"
    TEST_REPORT = "TEST_REPORT"
    CERTIFICATION = "CERTIFICATION"
    REGULATION = "REGULATION"
    PROCESS_GUIDE = "PROCESS_GUIDE"
    FAQ = "FAQ"
    OTHER = "OTHER"


class LifecycleStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    WITHDRAWN = "WITHDRAWN"


class ProcessingStatus(StrEnum):
    REGISTERED = "REGISTERED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    INDEXING = "INDEXING"
    INDEXED = "INDEXED"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"


class AccessClass(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL_NONCONFIDENTIAL = "INTERNAL_NONCONFIDENTIAL"
    BLOCKED = "BLOCKED"


class LifecycleEventType(StrEnum):
    CREATED = "CREATED"
    ACTIVATED = "ACTIVATED"
    SUPERSEDED = "SUPERSEDED"
    WITHDRAWN = "WITHDRAWN"
    REACTIVATED = "REACTIVATED"
    CORRECTED = "CORRECTED"


class LifecycleResultStatus(StrEnum):
    RESOLVED = "RESOLVED"
    NOT_CREATED = "NOT_CREATED"
    CONFLICT = "CONFLICT"
    UNRESOLVED = "UNRESOLVED"
    INVALID = "INVALID"


class LocatorRole(StrEnum):
    GOLD = "GOLD"
    RUNTIME = "RUNTIME"


class LocatorStatus(StrEnum):
    PLANNED = "PLANNED"
    MATERIALIZED = "MATERIALIZED"
    VERIFIED = "VERIFIED"
    INVALID = "INVALID"


class MappingStatus(StrEnum):
    EXACT = "EXACT"
    SPLIT = "SPLIT"
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


# More specific public aliases keep meaning explicit without duplicating values.
LocatorMappingStatus = MappingStatus
RenderMappingStatus = MappingStatus


class SourceRenderMappingStatus(StrEnum):
    MAPPED = "MAPPED"
    UNMAPPED = "UNMAPPED"
    FAILED = "FAILED"


class MappingKind(StrEnum):
    ONE_TO_ONE = "ONE_TO_ONE"
    EXPANSION = "EXPANSION"
    CONTRACTION = "CONTRACTION"
    DELETION = "DELETION"


CustomerMappingKind = MappingKind


class FieldStatus(StrEnum):
    EXPLICIT = "EXPLICIT"
    DERIVED = "DERIVED"
    MISSING = "MISSING"
    AMBIGUOUS = "AMBIGUOUS"
    CONFLICTING = "CONFLICTING"
    SUPERSEDED = "SUPERSEDED"


FieldAnnotationStatus = FieldStatus


class ValueState(StrEnum):
    KNOWN = "KNOWN"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNSET = "UNSET"
    UNRESOLVED = "UNRESOLVED"


class NormalizationStatus(StrEnum):
    NOT_REQUESTED = "NOT_REQUESTED"
    NORMALIZED = "NORMALIZED"
    UNRESOLVED = "UNRESOLVED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class Comparator(StrEnum):
    EQ = "EQ"
    LT = "LT"
    LTE = "LTE"
    GT = "GT"
    GTE = "GTE"
    BETWEEN = "BETWEEN"
    APPROX = "APPROX"


MeasurementComparator = Comparator


class FactKind(StrEnum):
    SPECIFICATION = "SPECIFICATION"
    TYPICAL_VALUE = "TYPICAL_VALUE"
    SINGLE_TEST_RESULT = "SINGLE_TEST_RESULT"
    RECOMMENDED_RANGE = "RECOMMENDED_RANGE"
    LIMITATION = "LIMITATION"


class AuthorityClass(StrEnum):
    REGULATORY = "REGULATORY"
    APPROVED_SPECIFICATION = "APPROVED_SPECIFICATION"
    APPROVED_TEST_REPORT = "APPROVED_TEST_REPORT"
    APPROVED_GUIDANCE = "APPROVED_GUIDANCE"
    UNVERIFIED = "UNVERIFIED"
    SYNTHETIC_DEMO = "SYNTHETIC_DEMO"


class EvidenceRelation(StrEnum):
    SUPPORTS = "SUPPORTS"
    QUALIFIES = "QUALIFIES"
    CONTRADICTS = "CONTRADICTS"


CitationRelation = EvidenceRelation


class SupportLevel(StrEnum):
    DIRECT = "DIRECT"
    PARTIAL = "PARTIAL"


class VerificationStatus(StrEnum):
    EXACT_MATCH = "EXACT_MATCH"
    STALE = "STALE"
    MISMATCH = "MISMATCH"
    INELIGIBLE = "INELIGIBLE"


class ClaimType(StrEnum):
    FACT = "FACT"
    CUSTOMER_STATEMENT = "CUSTOMER_STATEMENT"
    ASSUMPTION = "ASSUMPTION"
    UNKNOWN = "UNKNOWN"


class SupportStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    QUALIFIED = "QUALIFIED"
    CONFLICTED = "CONFLICTED"
    UNSUPPORTED = "UNSUPPORTED"


ClaimSupportStatus = SupportStatus


class QAOutcome(StrEnum):
    ANSWERED = "ANSWERED"
    PARTIAL = "PARTIAL"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    REFUSED = "REFUSED"


class RequirementStatus(StrEnum):
    COMPLETE = "COMPLETE"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    BLOCKED = "BLOCKED"


class DraftPurpose(StrEnum):
    CLARIFICATION = "CLARIFICATION"
    TECHNICAL_RESPONSE = "TECHNICAL_RESPONSE"


ReplyPurpose = DraftPurpose


class ReviewStatus(StrEnum):
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ReviewDecisionType(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    REQUEST_CHANGES = "REQUEST_CHANGES"


class CaseStatus(StrEnum):
    NEW = "NEW"
    ANALYZED = "ANALYZED"
    AWAITING_CUSTOMER = "AWAITING_CUSTOMER"
    EVIDENCE_READY = "EVIDENCE_READY"
    DRAFT_READY = "DRAFT_READY"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"


class EnvironmentNamespace(StrEnum):
    DEVELOPMENT = "DEVELOPMENT"
    SEALED_HOLDOUT = "SEALED_HOLDOUT"


class DatasetSplit(StrEnum):
    DEVELOPMENT = "DEVELOPMENT"
    SEALED_HOLDOUT = "SEALED_HOLDOUT"


Split = DatasetSplit


class DatasetReleaseStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    FROZEN = "FROZEN"
    RETIRED = "RETIRED"


class TaskType(StrEnum):
    QA = "QA"
    REQUIREMENT_EXTRACTION = "REQUIREMENT_EXTRACTION"
    REPLY_DRAFT = "REPLY_DRAFT"
    REFUSAL = "REFUSAL"
    SECURITY = "SECURITY"


TaskLabel = TaskType


class RunStatus(StrEnum):
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    COMPLETE = "COMPLETE"
    INVALID = "INVALID"


class FreezeStatus(StrEnum):
    FROZEN = "FROZEN"
    INVALIDATED = "INVALIDATED"
    READY_FOR_INTEGRATION = "READY_FOR_INTEGRATION"
    NOT_READY = "NOT_READY"


class MeasurementStatus(StrEnum):
    PLANNED = "PLANNED"
    NOT_RUN = "NOT_RUN"
    MEASURED = "MEASURED"
    INVALID = "INVALID"


class ThresholdStatus(StrEnum):
    SET = "SET"


class Verdict(StrEnum):
    NOT_RUN = "NOT_RUN"
    PASS = "PASS"
    CONDITIONAL_PASS = "CONDITIONAL_PASS"
    FAIL = "FAIL"


EvaluationVerdict = Verdict


class LimitationStatus(StrEnum):
    APPLIES = "APPLIES"
    DOES_NOT_APPLY = "DOES_NOT_APPLY"
    UNRESOLVED = "UNRESOLVED"


class LimitationPlacement(StrEnum):
    INLINE = "INLINE"
    LIMITATIONS_SECTION = "LIMITATIONS_SECTION"
    REFUSAL_REASON = "REFUSAL_REASON"


DisclosurePlacement = LimitationPlacement


class LimitationAction(StrEnum):
    QUALIFY = "QUALIFY"
    REMOVE_CLAIM = "REMOVE_CLAIM"
    REFUSE = "REFUSE"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    HUMAN_REVIEW = "HUMAN_REVIEW"


LimitationResolutionAction = LimitationAction


class ApprovalStatus(StrEnum):
    APPROVED = "APPROVED"
    PENDING = "PENDING"
    UNVERIFIED = "UNVERIFIED"
    REJECTED = "REJECTED"


class HistoricalUsePolicy(StrEnum):
    ALLOWED_WITH_DISCLOSURE = "ALLOWED_WITH_DISCLOSURE"
    AUDIT_ONLY = "AUDIT_ONLY"
    PROHIBITED = "PROHIBITED"


class RevisionStatus(StrEnum):
    DRAFT = "DRAFT"
    FROZEN = "FROZEN"
    RETIRED = "RETIRED"
    INVALID = "INVALID"


class AttributionStatus(StrEnum):
    EXACT_MATCH = "EXACT_MATCH"
    INVALID = "INVALID"


class NormalizationMapStatus(StrEnum):
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class CustomerSourceChannel(StrEnum):
    MANUAL_PASTE = "MANUAL_PASTE"
    PASTED_EMAIL = "PASTED_EMAIL"
    PASTED_CHAT = "PASTED_CHAT"


class SenderRole(StrEnum):
    CUSTOMER = "CUSTOMER"
    SALES = "SALES"
    TECHNICAL_SUPPORT = "TECHNICAL_SUPPORT"
    SYSTEM = "SYSTEM"


class DataClassification(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class RedactionStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    REDACTED = "REDACTED"
    BLOCKED = "BLOCKED"


class RefusalCode(StrEnum):
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    NO_ACTIVE_SOURCE_VERSION = "NO_ACTIVE_SOURCE_VERSION"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    UNSUPPORTED_SOURCE_FORMAT = "UNSUPPORTED_SOURCE_FORMAT"
    SENSITIVE_DATA_BLOCKED = "SENSITIVE_DATA_BLOCKED"
    PROMPT_INJECTION_RISK = "PROMPT_INJECTION_RISK"
    UNVERIFIABLE_UNIT = "UNVERIFIABLE_UNIT"
    MISSING_BLOCKING_CONTEXT = "MISSING_BLOCKING_CONTEXT"
    PROHIBITED_ACTION = "PROHIBITED_ACTION"


class ErrorCode(StrEnum):
    INVALID_SCHEMA = "INVALID_SCHEMA"
    NOT_FOUND = "NOT_FOUND"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    SEMANTIC_VALIDATION_FAILED = "SEMANTIC_VALIDATION_FAILED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    LIFECYCLE_NOT_YET_CREATED = "LIFECYCLE_NOT_YET_CREATED"
    LIFECYCLE_VERSION_GAP = "LIFECYCLE_VERSION_GAP"
    LIFECYCLE_EVENT_MISSING = "LIFECYCLE_EVENT_MISSING"
    LIFECYCLE_EVENT_CONFLICT = "LIFECYCLE_EVENT_CONFLICT"
    LIFECYCLE_INTERVAL_INVALID = "LIFECYCLE_INTERVAL_INVALID"
    LIFECYCLE_CORRECTION_INVALID = "LIFECYCLE_CORRECTION_INVALID"
    RENDER_MAPPING_PARTIAL = "RENDER_MAPPING_PARTIAL"
    RENDER_MAPPING_FAILED = "RENDER_MAPPING_FAILED"
    RENDER_RECEIPT_MISMATCH = "RENDER_RECEIPT_MISMATCH"
    UNSUPPORTED_TABLE_LOCATION = "UNSUPPORTED_TABLE_LOCATION"
    UNSUPPORTED_COMPLEX_TABLE = "UNSUPPORTED_COMPLEX_TABLE"
    UNSUPPORTED_CROSS_PAGE_TABLE = "UNSUPPORTED_CROSS_PAGE_TABLE"
    CUSTOMER_OFFSET_MAPPING_FAILED = "CUSTOMER_OFFSET_MAPPING_FAILED"
    SIDECAR_IDEMPOTENCY_CONFLICT = "SIDECAR_IDEMPOTENCY_CONFLICT"
    RESUME_CONTEXT_MISMATCH = "RESUME_CONTEXT_MISMATCH"
